
spring.datasource.url=jdbc:postgresql://localhost:5432/urbanpulse
spring.datasource.username=postgres
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=none


spring.sql.init.mode=always